plugin: azure.azcollection.azure_rm

include_vm_resource_groups:
  - rg-winrm-demo

auth_source: auto

# Map the first private IP to ansible_host
compose:
  ansible_host: "{{ private_ips[0] }}"

# Static connection parameters
ansible_connection: winrm
ansible_winrm_transport: ssl
ansible_port: 5985
ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
ansible_winrm_server_cert_validation: ignore
