plugin: azure.azcollection.azure_rm
include_vm_resource_groups:
  - rg-winrm-demo   # matches your Terraform RG
auth_source: auto
compose:
  ansible_host: "{{ private_ips[0] }}"
  ansible_connection: winrm
  ansible_winrm_transport: ssl
  ansible_port: 5985
  ansible_user: "{{ lookup('env', 'ANSIBLE_USER') }}"
  ansible_password: "{{ lookup('env', 'ANSIBLE_PASSWORD') }}"
  ansible_winrm_server_cert_validation: ignore

groups:
  windows: "'vm-winrm-demo' in name"
