- name: Test Windows VM
  hosts: windows
  gather_facts: no
  tasks:
    - name: Ensure hostname
      win_hostname:
        name: "winrm-demo"

    - name: Create test file
      win_file:
        path: C:\Temp\spacelift_test.txt
        state: touch
